apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: dm-hw20-eks-cluster  # Name of the EKS cluster.
  region: us-east-1
  version: "1.25" # Kubernetes version of the EKS cluster

nodeGroups: # List of node groups that will be created in the EKS cluster.
  - name: ng-1 # Name of the first node group.
    instanceType: t2.micro # EC2 instance type for the node group.
    desiredCapacity: 2 # Number of desired nodes for the node group.
    iam: # IAM configuration for the node group.
      withAddonPolicies:
        albIngress: true # Enable the ALB Ingress Controller addon policy.
    # ssh:
    #   allow: true # Enable SSH access to the nodes in the node group.
        # sshPublicKeyPath: /path/to/public/key # Path to your public key file
    minSize: 1 # Minimum number of nodes in the node group.
    maxSize: 2 # Maximum number of nodes in the node group.

# availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d, 'us-east-1e', 'us-east-1f']  # Exclude  'us-east-1e' - because here has a problems
