
apiVersion: v1              # The API version for the Kubernetes resource.
kind: Service               # The type of Kubernetes resource.
metadata:                   # Metadata for the resource.
  name: my-load-balancer    # The name of the service.
spec:                       # Specification for the resource.
  type: LoadBalancer        # Expose the service outside the cluster using a cloud load balancer.
  selector:
    app: php                # Selects the set of Pods targeted by the Service.
  ports:                    # List of ports to expose on the .service.
  - name: http
    port: 80                # The port number.
    targetPort: 80
    protocol: TCP

---
apiVersion: v1              # The API version for the Kubernetes resource.
kind: Service               # The type of Kubernetes resource.
metadata:                   # Metadata for the resource.
  name: dm-hw20-php-service  # The name of the service.
spec:                       # Specification for the resource.
  selector:                 # Selects the set of Pods targeted by the Service.
    app: php                # Label for the application name.
    tier: backend           # Label for the tier of the application.
  ports:                    # List of ports to expose on the .service.
  - name: http
    port: 80                # The port number.
    targetPort: 80
    protocol: TCP
