apiVersion: apps/v1         # The API version for the Kubernetes resource.
kind: Deployment            # The type of Kubernetes resource.

metadata:                   # Metadata for the resource.
  name: hello-universe  # The name of the deployment.
  labels:  # Key-value pairs used to label and organize the resource.
    app: php
    tier: backend           # Label for the tier of the application.

spec:                       # Specification for the resource.
  replicas: 1               # The desired number of replicas for the deployment.
  selector:                 # Selects the set of Pods targeted by the deployment.
    matchLabels:            # The labels used for Pod selection.
      app: hello-universe              # Label for the application name.
  template:  # The template used to create new Pods for the deployment.
    metadata:
      labels:
        app: hello-universe            # Label for the application name.
    spec:
      containers:           # List of containers belonging to the Pod.
      - name: hello-universe           # Name of the container.
        # The Docker image used for the container.
        image: mpetason/hello-universe
        ports:
        - containerPort: 8080