apiVersion: v1              # The API version for the Kubernetes resource.
kind: Service               # The type of Kubernetes resource.

metadata:                   # Metadata for the resource.
  name: hello-universe  # The name of the service.
  labels:  # Key-value pairs used to label and organize the resource.
    app: php
    tier: backend           # Label for the tier of the application.

spec:                       # Specification for the resource.
  selector:                 # Selects the set of Pods targeted by the Service.
    app: hello-universe                # Label for the application name.
  ports:                    # List of ports to expose on the .service.
  - port: 8080                # The port number.
  # externalIPs:           # The external IP addresses associated with the service.
  # - 0.0.0.0/0       # The public IP address of the service.