# Build Docker php page image.
# Triggered on push to main branch and pull requests to main branch.
name: Build and Deploy PHP Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code.
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to Dockerhub.
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Build and push the Docker image.
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: macrosolid/phpwebpage:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get pods
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: get pods

      - name: Configure kubectl
        uses: steebchen/kubectl@v2.1.1
        with:
          # version: "1.26.3"
          kuberconfig: ${{ secrets.KUBECONFIG  }}
          server: https://48823EB3617FACDB656C1D5624CB4F24.gr7.us-east-1.eks.amazonaws.com:443

      - name: Apply Kubernetes manifests
        run: |
          kubectl version
          kubectl get nodes
          kubectl config view
          kubectl apply -f php_service.yaml
          sleep 10
          kubectl apply -f php_deployment.yaml
