name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get smart tag
      id: prepare
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/phpwebpage

    - id: prepare1
      uses: Surgo/docker-smart-tag-action@v1
      with:
        docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/phpwebpage
    - run: echo ${{ steps.prepare1.outputs.tag }}

    - id: prepare2
      uses: docker/build-push-action@v2
      with:
        docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/phpwebpage
        tag_with_sha: true
    - run: echo ${{ steps.prepare2.outputs.tag }}

    - id: prepare3
      uses: docker/build-push-action@v2
      with:
        docker_image: ${{ secrets.DOCKERHUB_USERNAME }}/phpwebpage
        default_branch: ${{ github.event.repository.default_branch }}
    - run: echo ${{ steps.prepare3.outputs.tag }}


        
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     default_branch: ${{ github.event.repository.default_branch }}
    #     tags: ${{ steps.prepare.outputs.tag }}